### ISSUE TITLE
Unable to download pre-trained models 

### ISSUE THREAD

**Issue by Shivvrat** [epic-kitchens/VISOR-HOS#9]
Hello. I am not able to download the pre-trained models using the following script - 
`mkdir checkpoints && cd checkpoints
wget -O model_final_hos.pth https://www.dropbox.com/s/xi3249dbamv9wzs/model_final_hos.pth?dl=0
wget -O model_final_active.pth https://www.dropbox.com/s/jner6mn0hogmbav/model_final_active.pth?dl=0
cd ..`
It seems the file has been deleted. Getting this error - "This item was deleted
You might be able to find it in your deleted files. If it's not there, try asking the person who shared it with you."

**Comment by ddshan** [comment]
Hi, 

Really sorry for the inconvenience. 
We have updated the links to download the models. They should work now.
